-- liquibase formatted sql


-- changeset moaz:1756449637432-1
-- precondition onFail:MARK_RAN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = '_user' ;
CREATE TABLE "_user" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
"email" VARCHAR(255) NOT NULL UNIQUE, "first_name" VARCHAR(255),
"last_name" VARCHAR(255), "password" VARCHAR(255) NOT NULL,
"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
"role" VARCHAR(255),
CONSTRAINT "_user_pkey" PRIMARY KEY ("id")
);
CREATE SEQUENCE  IF NOT EXISTS "_user_seq" AS bigint START WITH 1 INCREMENT BY 50 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
--rollback drop table _user;
--rollback drop sequence _user_seq;


-- changeset ihab:create-category-table
-- precondition onFail:MARK_RAN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'category' ;
CREATE TABLE "category" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
"name" VARCHAR(255) NOT NULL UNIQUE,
"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
"updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT "category_pkey" PRIMARY KEY ("id"));
CREATE SEQUENCE  IF NOT EXISTS "category_seq" AS bigint START WITH 1 INCREMENT BY 50 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
--rollback drop table category;
--rollback drop sequence category_seq;

--this is for product

-- changeset ihab:create-product-table
-- precondition onFail:MARK_RAN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'product' ;
CREATE TABLE "product" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
"category_id" BIGINT NOT NULL,
"price" DECIMAL(10,2) NOT NULL,
"name" VARCHAR(255) NOT NULL,
"brand" VARCHAR(255),
"description" TEXT,
"amount" INTEGER,
CONSTRAINT "product_pkey" PRIMARY KEY ("id"),
CONSTRAINT "product_fkey" FOREIGN KEY ("category_id") REFERENCES "category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE SEQUENCE  IF NOT EXISTS "product_seq" AS bigint START WITH 1 INCREMENT BY 50 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
--rollback drop table product;
--rollback drop sequence product_seq;


-- changeset ihab:create-media-table
-- precondition onFail:MARK_RAN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'media' ;
CREATE TABLE "media" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
"url" VARCHAR(255),
"file_name" VARCHAR(255),
"file_type" VARCHAR(255),
"cloudinary_public_id" VARCHAR(255),
"uploaded_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
"product_id" BIGINT NOT NULL,
CONSTRAINT "media_pkey" PRIMARY KEY ("id"),
CONSTRAINT "media_fkey" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION
);
CREATE SEQUENCE  IF NOT EXISTS "media_seq" AS bigint START WITH 1 INCREMENT BY 50 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
--rollback drop table media;
--rollback drop sequence media_seq;


-- changeset ihab:create-cart-table
-- precondition onFail:MARK_RAN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'cart' ;
CREATE TABLE "cart" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
"total_price" DECIMAL(10,2),
"is_active" BOOLEAN DEFAULT TRUE,
"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
"updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
"user_id" BIGINT NOT NULL,
CONSTRAINT "cart_pkey" PRIMARY KEY ("id"),
CONSTRAINT "cart_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION
);
CREATE SEQUENCE  IF NOT EXISTS "cart_seq" AS bigint START WITH 1 INCREMENT BY 50 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
--rollback drop table cart;
--rollback drop sequence cart_seq;

-- changeset ihab:create-cart_item-table
-- precondition onFail:MARK_RAN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'cart_item' ;
CREATE TABLE "cart_item" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
"total_price" DECIMAL(10,2),
"unite_price" DECIMAL(10,2),
"quantity" INTEGER,
"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
"updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
"cart_id" BIGINT NOT NULL,
"product_id" BIGINT NOT NULL,
CONSTRAINT "cart_item_pkey" PRIMARY KEY ("id"),
CONSTRAINT "cart_item_cart_fkey" FOREIGN KEY ("cart_id") REFERENCES "cart"("id") ON DELETE CASCADE ON UPDATE NO ACTION
CONSTRAINT "cart_item_product_fkey" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION
);
CREATE SEQUENCE  IF NOT EXISTS "cart_item_seq" AS bigint START WITH 1 INCREMENT BY 50 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
--rollback drop table cart_item;
--rollback drop sequence cart_item_seq;