-- liquibase formatted sql


-- changeset moaz:1756449637432-1
CREATE TABLE "_user" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
"email" VARCHAR(255) NOT NULL UNIQUE, "first_name" VARCHAR(255),
"last_name" VARCHAR(255), "password" VARCHAR(255) NOT NULL,
"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
"role" VARCHAR(255),
CONSTRAINT "_user_pkey" PRIMARY KEY ("id")
);
--rollback drop table _user;


-- changeset ihab:create-category-table
CREATE TABLE "category" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
"name" VARCHAR(255) NOT NULL UNIQUE,
"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
"updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT "category_pkey" PRIMARY KEY ("id"));
--rollback drop table category;


-- changeset ihab:create-product-table
-- precondition onFail:MARK_RAN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'product' ;
CREATE TABLE "product" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
"category_id" BIGINT NOT NULL,
"price" DECIMAL(10,2) NOT NULL,
"name" VARCHAR(255) NOT NULL,
"brand" VARCHAR(255),
"description" TEXT,
"amount" INTEGER,
"user_id" BIGINT NOT NULL,
CONSTRAINT "product_pkey" PRIMARY KEY ("id"),
CONSTRAINT "vendor_fkey" FOREIGN KEY ("user_id") REFERENCES "_user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT "product_fkey" FOREIGN KEY ("category_id") REFERENCES "category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
--rollback drop table product;


-- changeset ihab:create-media-table
CREATE TABLE "media" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
"url" VARCHAR(255),
"file_name" VARCHAR(255),
"file_type" VARCHAR(255),
"cloudinary_public_id" VARCHAR(255) UNIQUE,
"is_cover_image" BOOLEAN DEFAULT FALSE,
"uploaded_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
"product_id" BIGINT NOT NULL,
CONSTRAINT "media_pkey" PRIMARY KEY ("id"),
CONSTRAINT "media_fkey" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION
);
--rollback drop table media;


-- changeset ihab:create-cart-table
CREATE TABLE "cart" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
"total_price" DECIMAL(10,2),
"is_active" BOOLEAN DEFAULT TRUE,
"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
"updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
"user_id" BIGINT NOT NULL,
CONSTRAINT "cart_pkey" PRIMARY KEY ("id"),
CONSTRAINT "cart_fkey" FOREIGN KEY ("user_id") REFERENCES "_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION
);
--rollback drop table cart;

-- changeset ihab:create-cart_item-table
CREATE TABLE "cart_item" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
"total_price" DECIMAL(10,2),
"unite_price" DECIMAL(10,2),
"quantity" INTEGER,
"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
"updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
"cart_id" BIGINT NOT NULL,
"product_id" BIGINT NOT NULL,
CONSTRAINT "cart_item_pkey" PRIMARY KEY ("id"),
CONSTRAINT "cart_item_cart_fkey" FOREIGN KEY ("cart_id") REFERENCES "cart"("id") ON DELETE CASCADE ON UPDATE NO ACTION,
CONSTRAINT "cart_item_product_fkey" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION
);
--rollback drop table cart_item;


-- changeset ihab:create-order-table
CREATE TABLE "customer_order" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
"total_price" DECIMAL(10,2),
"order_statues" VARCHAR(250),
"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
"updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
"user_id" BIGINT NOT NULL,
CONSTRAINT "order_pkey" PRIMARY KEY ("id"),
CONSTRAINT "order_fkey" FOREIGN KEY ("user_id") REFERENCES "_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION
);
--rollback drop table order;

-- changeset ihab:create-order_item-table
CREATE TABLE "customer_order_item" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
"total_price" DECIMAL(10,2),
"unite_price" DECIMAL(10,2),
"quantity" INTEGER,
"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
"updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
"order_id" BIGINT NOT NULL,
"product_id" BIGINT NOT NULL,
CONSTRAINT "order_item_pkey" PRIMARY KEY ("id"),
CONSTRAINT "customer_order_item_customer_order_fkey" FOREIGN KEY ("order_id") REFERENCES "customer_order"("id") ON DELETE CASCADE ON UPDATE NO ACTION,
CONSTRAINT "order_item_product_fkey" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION
);
--rollback drop table order_item;

-- changeset ihab:alter-product-table-create-review-table
ALTER TABLE product ADD avg_rating INTEGER DEFAULT 0.0;


CREATE TABLE "review" (
"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
"content" TEXT,
"rating" INTEGER,
"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
"user_id" BIGINT NOT NULL,
"product_id" BIGINT NOT NULL,
CONSTRAINT "review_pkey" PRIMARY KEY ("id"),
CONSTRAINT "review_user_fkey" FOREIGN KEY ("user_id") REFERENCES "_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION,
CONSTRAINT "review_product_fkey" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION
);

--rollback alter table review drop column avg_rating;
--rollback drop table review;


