-- liquibase formatted sql


-- changeset moaz:1756449637432-1
-- precondition onFail:MARK_RAN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = '_user' ;
CREATE TABLE "_user" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "email" VARCHAR(255), "first_name" VARCHAR(255), "last_name" VARCHAR(255), "password" VARCHAR(255), "role" VARCHAR(255), CONSTRAINT "_user_pkey" PRIMARY KEY ("id"));
CREATE SEQUENCE  IF NOT EXISTS "_user_seq" AS bigint START WITH 1 INCREMENT BY 50 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
--rollback drop table _user;
--rollback drop sequence _user_seq;


-- changeset moaz:sample-data
-- precondition onFail:MARK_RAN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from _user ;
insert into _user(id, email, first_name, last_name, password) values(1, 'ehab@gmail.com', 'ehab', 'khalil', '124545');
-- rollback truncate table _user;